import titles from "./wikipedia-titles.json";

/**
 * A short description of the selected object from English Wikipedia, fetched
 * live and shown with its credit. Like the cloud forecast it is third-party
 * text beside the astronomy, never part of it, and simply absent offline.
 *
 * Only the object-to-article mapping ships with the atlas (generated by
 * scripts/build-wikipedia-titles.py); the prose is CC BY-SA 4.0 and stays on
 * Wikipedia. The REST summary endpoint sends `access-control-allow-origin: *`,
 * so it also works for the portable release opened from a file.
 */
const ENDPOINT = "https://en.wikipedia.org/api/rest_v1/page/summary/";

export type WikiSummary =
  | { state: "loading" }
  | { state: "ready"; title: string; extract: string; url: string }
  | { state: "unavailable" };

export function wikiTitle(id: string): string | null {
  return (titles as Record<string, string>)[id] ?? null;
}

// One request per article per session: re-selecting an object is instant and
// does not spend Wikipedia's rate limit.
const cache = new Map<string, WikiSummary>();

export async function fetchWikiSummary(title: string, signal: AbortSignal): Promise<WikiSummary> {
  const cached = cache.get(title);
  if (cached) return cached;
  try {
    const response = await fetch(ENDPOINT + encodeURIComponent(title.replace(/ /g, "_")), {
      signal,
    });
    if (!response.ok) return { state: "unavailable" };
    const page: {
      title?: string;
      extract?: unknown;
      content_urls?: { desktop?: { page?: string } };
    } = await response.json();
    if (typeof page.extract !== "string" || !page.extract) return { state: "unavailable" };
    const result: WikiSummary = {
      state: "ready",
      title: page.title ?? title,
      extract: page.extract,
      url: page.content_urls?.desktop?.page ?? "https://en.wikipedia.org/wiki/" + title,
    };
    cache.set(title, result);
    return result;
  } catch (error) {
    if (signal.aborted) throw error;
    return { state: "unavailable" };
  }
}
